import { Intern, Task } from "../types";

export const mockInterns: Intern[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.johnson@example.com",
    role: "Frontend Developer",
    department: "Engineering",
    startDate: "2024-01-15",
    skills: ["React", "TypeScript", "Tailwind CSS", "JavaScript"],
    performanceScore: 85,
    status: "good",
    mentor: "John Smith",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    bio: "Enthusiastic frontend developer with passion for UI/UX",
  },
  {
    id: "2",
    name: "Michael Chen",
    email: "michael.chen@example.com",
    role: "Backend Developer",
    department: "Engineering",
    startDate: "2024-02-01",
    skills: ["Node.js", "Python", "PostgreSQL", "Docker"],
    performanceScore: 72,
    status: "average",
    mentor: "Emma Davis",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
    bio: "Backend specialist focusing on system design",
  },
  {
    id: "3",
    name: "Jessica Lee",
    email: "jessica.lee@example.com",
    role: "Product Designer",
    department: "Design",
    startDate: "2024-01-22",
    skills: ["Figma", "UI Design", "UX Research", "Prototyping"],
    performanceScore: 88,
    status: "good",
    mentor: "Alex Rivera",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica",
    bio: "Creative designer with eye for detail",
  },
  {
    id: "4",
    name: "David Park",
    email: "david.park@example.com",
    role: "Data Analyst",
    department: "Analytics",
    startDate: "2024-02-10",
    skills: ["Python", "SQL", "Tableau", "Statistics"],
    performanceScore: 65,
    status: "needs-improvement",
    mentor: "Sarah Martinez",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
    bio: "Analytical thinker learning the ropes",
  },
  {
    id: "5",
    name: "Emma Wilson",
    email: "emma.wilson@example.com",
    role: "QA Engineer",
    department: "Quality Assurance",
    startDate: "2024-01-29",
    skills: ["Testing", "Automation", "Selenium", "JIRA"],
    performanceScore: 79,
    status: "average",
    mentor: "Robert Taylor",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma",
    bio: "Detail-oriented QA professional",
  },
];

export const mockTasks: Task[] = [
  {
    id: "task-1",
    title: "Implement user authentication",
    description: "Add JWT-based authentication to the API",
    assignedIntern: "1",
    priority: "high",
    status: "in-progress",
    dueDate: "2024-03-15",
    createdAt: "2024-03-01",
    updatedAt: "2024-03-08",
  },
  {
    id: "task-2",
    title: "Design dashboard mockups",
    description: "Create high-fidelity Figma mockups for the dashboard",
    assignedIntern: "3",
    priority: "high",
    status: "review",
    dueDate: "2024-03-12",
    createdAt: "2024-02-28",
    updatedAt: "2024-03-09",
  },
  {
    id: "task-3",
    title: "Write database migrations",
    description: "Create migrations for user and task tables",
    assignedIntern: "2",
    priority: "medium",
    status: "todo",
    dueDate: "2024-03-20",
    createdAt: "2024-03-05",
    updatedAt: "2024-03-05",
  },
  {
    id: "task-4",
    title: "Setup test environment",
    description: "Configure Vitest and write initial test suite",
    assignedIntern: "5",
    priority: "medium",
    status: "in-progress",
    dueDate: "2024-03-18",
    createdAt: "2024-03-02",
    updatedAt: "2024-03-07",
  },
  {
    id: "task-5",
    title: "API documentation",
    description: "Document all REST endpoints with OpenAPI spec",
    assignedIntern: "2",
    priority: "low",
    status: "done",
    dueDate: "2024-03-10",
    createdAt: "2024-02-25",
    updatedAt: "2024-03-10",
  },
  {
    id: "task-6",
    title: "Analytics dashboard",
    description: "Build interactive analytics dashboard with charts",
    assignedIntern: "4",
    priority: "medium",
    status: "todo",
    dueDate: "2024-03-25",
    createdAt: "2024-03-05",
    updatedAt: "2024-03-05",
  },
];
